Added the requirements of the folder structure
feedzai/feedzai-openml-python pull request #10
Opened 2018-06-25 09:09 UTC by krisztinaknagy

Added the requirements of the folder structure when using the provider in Pulse.

2018-06-25 09:12 UTC, pedrorijo91 commented on openml-scikit/README.md
> +When the user [imports a model](https://docs.feedzai.com/display/pulse/Importing+an+external+model) to Pulse using this provider, the import assumes a folder called ```model```, containing a pickle f
this link is not public, and as such it doesn't make sense to be linked from this public repository

2018-06-25 09:12 UTC, TravisBuddy commented
Hey @krisztinaknagy,  
Your changes look good to me!

2018-06-25 09:13 UTC, pedrorijo91 commented on openml-scikit/README.md
> +When the user [imports a model](https://docs.feedzai.com/display/pulse/Importing+an+external+model) to Pulse using this provider, the import assumes a folder called ```model```, containing a pickle f
probably Pulse is not known to readers. Maybe call it "Feedzai platform" is more understandable

2018-06-25 09:13 UTC, pedrorijo91 requested changes
remove the link to private Feedzai pages

2018-06-25 09:17 UTC, pedrorijo91 approved these changes
nice :) will merge soon if no one has anything more to say on this

2018-06-25 09:21 UTC, TravisBuddy commented
Hey @krisztinaknagy,  
Your changes look good to me!

2018-06-25 09:33 UTC, pedrorijo91 approved these changes

2018-06-25 11:11 UTC, nmldiegues commented on openml-scikit/README.md
> +When the user imports a model to the Feedzai platform using this provider, the import assumes a folder called ```model```, containing a pickle file (.pkl).
I usually like to give examples like Unix "tree" command.
E.g.: 

(don't use this *literal* example :) )

`nuno.diegues@Laptop-511:~/workspace/feedzai-openml-python/openml-scikit/src/test/resources$ tree
.
├── no_probability
│   └── model
│       └── svc_no_proba.joblib.pkl
├── rf
│   └── model
│       └── svc__rf_proba.joblib.pkl
└── svm
    ├── model
    │   └── svc.joblib.pkl
    └── model.json
`

2018-06-25 11:11 UTC, nmldiegues commented on openml-scikit/README.md
> +When the user imports a model to the Feedzai platform using this provider, the import assumes a folder called ```model```, containing a pickle file (.pkl).
Well, the indentation is not working great, so let's try with a screenshot:
![image](https://user-images.githubusercontent.com/889015/41847157-ef244538-7870-11e8-8b37-41661d761304.png)

2018-06-26 07:42 UTC, TravisBuddy commented
Hey @krisztinaknagy,  
Your changes look good to me!

2018-06-26 07:43 UTC, TravisBuddy commented
Hey @krisztinaknagy,  
Your changes look good to me!

2018-06-26 08:07 UTC, pedrorijo91 approved these changes

2018-06-26 08:11 UTC, merged

2018-06-26 08:12 UTC, nmldiegues commented
Merged and cherry picked to hf-0.1.X